name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: minimal_apitest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Wait for MySQL and create appuser
      run: |
        sudo apt-get update && sudo apt-get install mysql-client -y
        until mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} -e "SELECT 1;" ; do
          echo "Waiting for MySQL..."
          sleep 3
        done
        mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} -e "
          CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_PASSWORD }}';
          GRANT ALL PRIVILEGES ON minimal_apitest.* TO 'appuser'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Test
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: 127.0.0.1
        DB_USER: appuser
        DB_NAME: minimal_apitest
      run: dotnet test --no-build --verbosity normal

